// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksnyoasamhyunakuqdst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbnlvYXNhbWh5dW5ha3VxZHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODIyMjYsImV4cCI6MjA1OTQ1ODIyNn0.u-FxNC3blqcfQt9Q6BBdeKmfHUvsbK4eErlalntYnZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);